### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by worldsdream** [danielvalentin/Wordpress-fix-scandinavian-characters#1]
Hi, Does this still work? Because i have the latest wordpress version and in permainks i can't see the danish characters. If installing this plugin, will that work? For example right now I want tilbehør and it's showing tilbehoer in permalinks. Thank you

**Comment by danielvalentin** [comment]
Hi, that's exactly what this plugin does. it's obviously obsolete now. So, sorry. This isn't what you're looking for.
